DROP TABLE IF EXISTS TestUser;
CREATE TABLE TestUser (
    id TEXT PRIMARY KEY,
    name TEXT,
    email TEXT UNIQUE,
    data TEXT,
    config TEXT,
    point INTEGER DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS TestPost;
CREATE TABLE TestPost (
    id TEXT PRIMARY KEY,
    name TEXT,
    isPublished BOOLEAN DEFAULT FALSE,
    data TEXT,
    userId TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES TestUser(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TestNoId;
CREATE TABLE TestNoId (
    userId TEXT,
    postId TEXT,
    sample TEXT,
    UNIQUE(userId, postId)
);

DROP TABLE IF EXISTS TestOrder;
CREATE TABLE TestOrder (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    price INTEGER
);

DROP TABLE IF EXISTS TestExtend;
CREATE TABLE TestExtend (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT
);
