name = "kysely-worker-example"
main = "src/worker.ts"
compatibility_date = "2023-08-21"

[[ d1_databases ]]
binding = "D1_DB"
database_name = "public-test-db"
database_id = "58090851-7644-4494-9aea-f22c5e0e91d3"

[vars]
DB_API_KEY = "test-key"
